### PR TITLE
Do not strip the trailing slash

### LINKED ISSUE #29: Use "/" instead of "" for querying the model for the root page

### PR DESCRIPTION
**Pull request by mgechev**
Looks like, it was completely unnecessary to strip the trailing slash.

The tests are unrelated to the change.

Fix #29

### CODE REVIEW

**Comment by addyosmani** [comment]
Changes here looked fine, Minko. Have we verified this change continues to work as expected with one of the existing demo apps? I don't imagine it should alter anything otherwise.

**Comment by KyleAMathews** [comment]
The gatsby app needs changed as it accounts for this. I'm at react Europe this week but probably could quickly make the change in the morning.

**Comment by mgechev** [comment]
Yesterday I tested it with the existing applications and everything worked fine. Today I found another issue in the `guess-ga` package where:

```
/route/12
/route/32
```
Were both going to match `/route/:id/` which doesn't seem correct because of the trailing slash.

The latest commit fixes this issue and adds a few tests.

**Comment by addyosmani** [comment]
Thanks for catching those additional edge-cases, Minko. 

Would we be comfortable with landing this PR and testing out master (or an alpha tag) with Gatsby Wikipedia before making it an official release?

**Comment by mgechev** [comment]
👍

**Comment by addyosmani** [comment]
🎷

**Pull request merged**
